In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
from numpy.random import randn

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 =  Series([0,1,2],index=['T','U','V'])
ser2 =  Series([11,21],index=['A','B'])
pd.concat([ser1,ser2])

T     0
U     1
V     2
A    11
B    21
dtype: int64

In [7]:
pd.concat([ser1,ser2],axis=1)

0   1
A NaN  11
B NaN  21
T   0 NaN
U   1 NaN
V   2 NaN

In [8]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T     0
      U     1
      V     2
cat2  A    11
      B    21
dtype: int64

In [15]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['T','U','V'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['T','U','C'])

pd.concat([dframe1,dframe2])

C         T         U         V
0       NaN  1.456156  0.114900 -1.262070
1       NaN  0.453854 -0.027840  0.671415
2       NaN -2.655349  0.991111  0.451622
3       NaN -2.355870  1.938136  2.614821
0  0.496558  1.962491  1.711436       NaN
1 -2.326249  1.018258 -0.250393       NaN
2 -0.046144 -0.053240 -0.626202       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

C         T         U         V
0       NaN  1.456156  0.114900 -1.262070
1       NaN  0.453854 -0.027840  0.671415
2       NaN -2.655349  0.991111  0.451622
3       NaN -2.355870  1.938136  2.614821
4  0.496558  1.962491  1.711436       NaN
5 -2.326249  1.018258 -0.250393       NaN
6 -0.046144 -0.053240 -0.626202       NaN

In [ ]:
#check the link